import Head from "next/head";
import Image from "next/image";
import React from "react";
import styles from "../styles/Home.module.css";
import type { Spot } from "../types";

export default function Home() {
	const [data, setData] = React.useState<Spot[] | null>(null);

	React.useEffect(() => {
		const getData = async () => {
			const res = await fetch("/api/data");
			setData(await res.json());
		};

		getData();
	}, []);

	return (
		<div className={styles.container}>
			<Head>
				<title>Pwr Park</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>Pwr Park</h1>
				{data &&
					data.map(spot => (
						<span key={spot.id} className={styles.description}>
							{spot.name.full + " - " + spot.spots}
						</span>
					))}
			</main>
		</div>
	);
}
